version: '3'
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.6-r1-g0a3336c
    container_name: ddbj_validator_updater_virtuoso
    environment:
      DBA_PASSWORD: "dba"
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database"
      VIRT_Parameters_NumberOfBuffers: "680000"
      VIRT_Parameters_MaxDirtyBuffers: "500000"
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    ports:
      - ${DDBJ_VALIDATOR_UPDATER_VIRTUOSO_PORT:-58894}:8890
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/database:/database
      - ${PWD}/rdf_data:/rdf_data
