# frozen_string_literal: true
source "https://rubygems.org"

group :development do
  gem 'sinatra-reloader'
end

gem "rack"
gem "sinatra"
gem "haml"
gem "geocoder"
gem "pg"
gem "minitest"
gem "erubis"
gem "nokogiri"
