services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - virtuoso
    ports:
      - ${DDBJ_VALIDATOR_APP_PORT:-18840}:3000
    environment:
      TZ: Asia/Tokyo
      RUBY_YJIT_ENABLE: "true"
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DDBJ_VALIDATOR_APP_UNICORN_PORT: 3000
    user: 0:0
    volumes:
      - ${PWD}:/usr/src/ddbj_validator
      - ${DDBJ_VALIDATOR_APP_SHARED_HOST_DIR:-./shared}:/usr/src/ddbj_validator/shared
      - ${DDBJ_VALIDATOR_APP_VALIDATOR_LOG_HOST_DIR:-./logs}:/usr/src/ddbj_validator/logs
      - /home/ddbjshare/public/mirror_database/ftp.ncbi.nih.gov/ncbi_taxonomy/taxonomydb:/usr/src/ddbj_validator/conf/coll_dump
      - /lustre9/open/shared_data/db/config:/usr/src/ddbj_validator/conf/pub

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.6-r1-g0a3336c
    environment:
      DBA_PASSWORD: "dba"
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database"
      VIRT_Parameters_NumberOfBuffers: "170000"
      VIRT_Parameters_MaxDirtyBuffers: "130000"
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    ports:
      - ${DDBJ_VALIDATOR_VIRTUOSO_PORT:-18841}:8890
    user: 0:0
    volumes:
      - ${PWD}/shared/config/virtuoso:/settings
      - ${PWD}/shared/data/virtuoso:/database
