version: '3'
services:
  app:
    container_name: ${DDBJ_VALIDATOR_APP_CONTAINER_NAME:-ddbj_validator_app}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DDBJ_VALIDATOR_APP_IMAGE_NAME:-ddbj_validator_app}
    depends_on:
      - virtuoso
    networks:
      - ddbj
    ports:
      - ${DDBJ_VALIDATOR_APP_PORT:-18840}:3000
    environment:
      TZ: Asia/Tokyo
      DDBJ_VALIDATOR_APP_ROOT_PATH: ${DDBJ_ONTOLOGIES_APP_ROOT_DIR:-/usr/src/ddbj_validator/src}
      DDBJ_VALIDATOR_SHARED_PATH: ${DDBJ_ONTOLOGIES_SHARED_DIR:-/usr/src/ddbj_validator/shared}
      DDBJ_VALIDATOR_APP_UNICORN_PORT: 3000
      DDBJ_VALIDATOR_APP_VIRTUOSO_ENDPOINT_MASTER: ${DDBJ_VALIDATOR_APP_VIRTUOSO_ENDPOINT_MASTER:-http://virtuoso:8890/sparql}
      DDBJ_VALIDATOR_APP_NAMED_GRAPHE_URI_TAXONOMY: ${DDBJ_VALIDATOR_APP_NAMED_GRAPHE_URI_TAXONOMY:-http://ddbj.nig.ac.jp/ontologies/taxonomy}
      DDBJ_VALIDATOR_APP_POSTGRES_HOST: ${DDBJ_VALIDATOR_APP_POSTGRES_HOST}
      DDBJ_VALIDATOR_APP_POSTGRES_PORT: ${DDBJ_VALIDATOR_APP_POSTGRES_PORT}
      DDBJ_VALIDATOR_APP_POSTGRES_USER: ${DDBJ_VALIDATOR_APP_POSTGRES_USER}
      DDBJ_VALIDATOR_APP_POSTGRES_PASSWD: ${DDBJ_VALIDATOR_APP_POSTGRES_PASSWD}
      DDBJ_VALIDATOR_APP_POSTGRES_TIMEOUT: ${DDBJ_VALIDATOR_APP_POSTGRES_TIMEOUT:-30}
      DDBJ_VALIDATOR_APP_BIOSAMPLE_PACKAGE_VERSION: ${DDBJ_VALIDATOR_APP_BIOSAMPLE_PACKAGE_VERSION:-1.4.0}
      DDBJ_VALIDATOR_APP_GOOGLE_API_KEY: ${DDBJ_VALIDATOR_APP_GOOGLE_API_KEY:-your_api_key}
      DDBJ_VALIDATOR_APP_EUTILS_API_KEY: ${DDBJ_VALIDATOR_APP_EUTILS_API_KEY:-your_api_key}
      DDBJ_VALIDATOR_APP_MONITORING_SSUB_ID: ${DDBJ_VALIDATOR_APP_MONITORING_SSUB_ID:-SSUB009526}
      DDBJ_VALIDATOR_APP_VALIDATOR_LOG_DIR: ${DDBJ_VALIDATOR_APP_VALIDATOR_LOG_DIR:-/usr/src/ddbj_validator/logs}
      DDBJ_PARSER_APP_CONTAINER_NAME: ${DDBJ_PARSER_APP_CONTAINER_NAME:-ddbj.parser.app}
      DDBJ_PARSER_APP_CONTAINER_PORT: ${DDBJ_PARSER_APP_CONTAINER_PORT:-8080}
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/src:/usr/src/ddbj_validator/src
      - ${DDBJ_VALIDATOR_APP_SHARED_HOST_DIR:-./shared}:/usr/src/ddbj_validator/shared
      - ${DDBJ_VALIDATOR_APP_VALIDATOR_LOG_HOST_DIR:-./logs}:/usr/src/ddbj_validator/logs


  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.6-r1-g0a3336c
    container_name: ${DDBJ_VALIDATOR_VIRTUOSO_CONTAINER_NAME:-ddbj_validator_virtuoso}
    environment:
      DBA_PASSWORD: "dba"
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database"
      VIRT_Parameters_NumberOfBuffers: "170000"
      VIRT_Parameters_MaxDirtyBuffers: "130000"
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    networks:
      - ddbj
    ports:
      - ${DDBJ_VALIDATOR_VIRTUOSO_PORT:-18841}:8890
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/shared/config/virtuoso:/settings
      - ${PWD}/shared/data/virtuoso:/database

networks:
  ddbj:
    external:
      name: ${DDBJ_NETWORK_NAME:-ddbj}
