PREFIX ddbj_bs: <http://ddbj.nig.ac.jp/ontologies/biosample/>

SELECT DISTINCT ?attribute_name (REPLACE(STR(?attr_type), "http://ddbj.nig.ac.jp/ontologies/biosample/","") AS ?require_type) ?attribute_no
FROM <http://ddbj.nig.ac.jp/ontologies/biosample/<%= version %>>
{
  VALUES ?package_label { "<%= package_id %> package"@en }
  ?package rdfs:label ?package_label .
  ?axiom owl:annotatedSource ?package ;
    owl:annotatedTarget ?attr ;
    owl:annotatedProperty ?attr_type ;
    dc:identifier ?attribute_no .
  ?attr rdfs:subClassOf ddbj_bs:Attribute ;
    dc:identifier ?attribute_name .
  BIND( IF(?attr_type = ddbj_bs:has_mandatory_attribute, 1,  IF(?attr_type = ddbj_bs:has_optional_attribute, 2,  IF(?attr_type = ddbj_bs:has_attribute, 3, 0))) AS ?type_order)
} ORDER BY ?type_order ?attribute_no