PREFIX dbs: <http://ddbj.nig.ac.jp/ontologies/biosample/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?group_name ?attribute_name
FROM <http://ddbj.nig.ac.jp/ontologies/biosample/<%= version %>>
WHERE
{
  ?package rdfs:subClassOf dbs:DDBJ_Defined_Package ;
    rdfs:label "<%= package_name %> package"@en .
  ?restriction owl:domain ?package ;
    rdfs:label ?group_name ;
    rdfs:range ?range .
  ?range owl:oneOf/rdf:rest*/rdf:first ?attribute .
  ?axiom owl:annotatedTarget ?restriction ;
     owl:annotatedSource ?source ;
     rdfs:isDefinedBy dbs:Attribute_Group .
  ?attribute dc:identifier ?attribute_name ;
   rdfs:subClassOf dbs:Attribute .
} ORDER BY ?group_name