DEFINE sql:select-option "order"
PREFIX id-tax: <http://identifiers.org/taxonomy/>
PREFIX tax: <http://ddbj.nig.ac.jp/ontologies/taxonomy/>

SELECT DISTINCT ?tax_no
FROM <http://ddbj.nig.ac.jp/ontologies/taxonomy>
WHERE
{
  ?tax_id tax:scientificName "<%= organism_name %>" ;
    a tax:Taxon .
  BIND (REPLACE(STR(?tax_id), "http://identifiers.org/taxonomy/", "") AS ?tax_no)
}
