PREFIX id-tax: <http://identifiers.org/taxonomy/>
PREFIX tax: <http://ddbj.nig.ac.jp/ontologies/taxonomy/>

SELECT ?tax_id
FROM <<%=  tax_graph_uri %>>
WHERE
{
  VALUES ?tax_id { id-tax:<%= tax_id %> }
  VALUES ?plastid { tax:GeneticCode4 tax:GeneticCode11 }
  ?tax_id tax:geneticCodePt ?plastid .
} LIMIT 1
