PREFIX dbs: <http://ddbj.nig.ac.jp/ontologies/biosample/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT
 (REPLACE(?attr_name, " attribute", "") AS ?attribute) ?require
FROM <http://ddbj.nig.ac.jp/ontologies/biosample/<%= version %>>
WHERE
{
  ?package rdfs:subClassOf dbs:DDBJ_Defined_Package ;
    rdfs:label "<%= package_name %> package"@en .
  ?axiom owl:annotatedSource ?package ;
    dc:identifier ?attr_pkg_id ;
    owl:annotatedProperty  ?require_uri ;
    owl:annotatedTarget ?attr .
  ?attr rdfs:label ?attr_name .
  BIND (REPLACE(STR(?require_uri), "http://ddbj.nig.ac.jp/ontologies/biosample/", "") AS ?require)
} ORDER BY ?attr_pkg_id