PREFIX dbs: <http://ddbj.nig.ac.jp/ontologies/biosample/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT (COUNT(?package) AS ?count)
FROM <http://ddbj.nig.ac.jp/ontologies/biosample/<%= version %>>
WHERE
{
  VALUES ?package_id { "<%= package_name %>" }
  ?package rdfs:subClassOf dbs:DDBJ_Defined_Package ;
    dc:identifier ?package_id ;
    rdfs:label ?label .
}
