#!/usr/bin/env ruby
# 本番 (あるいは dev/compose.dev.yaml で起動中) の Virtuoso から、テストが参照する
# tax_id + その祖先 + スキーマ定義だけを抽出した最小の taxonomy.ttl を生成する
#
# 使い方:
#   DDBJ_VALIDATOR_APP_VIRTUOSO_ENDPOINT_MASTER=http://localhost:8890/sparql \
#   DDBJ_VALIDATOR_APP_NAMED_GRAPHE_URI_TAXONOMY=http://ddbj.nig.ac.jp/ontologies/taxonomy-private \
#     ruby test/fixtures/virtuoso/extract_taxonomy.rb > test/fixtures/virtuoso/taxonomy.ttl

require 'net/http'
require 'uri'
require 'set'
require 'json'

ENDPOINT = ENV.fetch('DDBJ_VALIDATOR_APP_VIRTUOSO_ENDPOINT_MASTER', 'http://localhost:8890/sparql')
GRAPH    = ENV.fetch('DDBJ_VALIDATOR_APP_NAMED_GRAPHE_URI_TAXONOMY', 'http://ddbj.nig.ac.jp/ontologies/taxonomy')

# テストコードと fixture から拾った tax_id (数値としてあり得ない 1111111111111 等は除外済み)
SEED_TAX_IDS = %w[
  1 2 561 562 1142 1148 1313 1314 1406378 1409 1416348 1445577 1515699
  1617264 5206 6231 7227 9606 10088 10090 10228 11320 1198036 12906
  103690 109903 1003037 1111708 1218073 1218099 1219033 1219034 1219044
  1219045 1219053 1219061 1223495 1223506 1223508 1223531 1223534
  1236543 1274375 1314752 2306576 282702 28384 32133 32644 410658
  447426 510903 539655 564289 655179 655401 662107 702656
].uniq

def sparql(query, format: 'text/turtle')
  uri  = URI(ENDPOINT)
  form = URI.encode_www_form('default-graph-uri' => GRAPH, 'query' => query, 'format' => format)
  res  = Net::HTTP.start(uri.host, uri.port, read_timeout: 120, open_timeout: 10) {|http|
    http.request(Net::HTTP::Post.new(uri.request_uri, 'Content-Type' => 'application/x-www-form-urlencoded'), form)
  }

  raise "SPARQL error (#{res.code}): #{res.body[0, 500]}" unless res.code.start_with?('2')

  res.body
end

puts "# Fixture extracted from #{GRAPH}"
puts '# Generated by test/fixtures/virtuoso/extract_taxonomy.rb'
puts '# DO NOT EDIT BY HAND — regenerate with the script above if seeds change'
puts

warn 'extracting schema (property + rank + genetic code definitions)...'
schema_query = <<~SPARQL
  PREFIX tax: <http://ddbj.nig.ac.jp/ontologies/taxonomy/>
  CONSTRUCT { ?s ?p ?o }
  WHERE {
    {
      ?s rdfs:subPropertyOf tax:name .
      ?s ?p ?o .
    } UNION {
      ?s rdfs:subClassOf tax:Rank .
      ?s ?p ?o .
    } UNION {
      ?s rdfs:subClassOf tax:GeneticCode .
      ?s ?p ?o .
    } UNION {
      VALUES ?s { tax:name tax:Rank tax:GeneticCode tax:Taxon }
      ?s ?p ?o .
    }
  }
SPARQL
puts sparql(schema_query)

# 祖先探索は transitive closure が重いので 1 tax_id ずつ
ancestors = Set.new
SEED_TAX_IDS.each do |id|
  warn "  ancestors of #{id} ..."
  q = <<~SPARQL
    SELECT DISTINCT ?a
    WHERE {
      <http://identifiers.org/taxonomy/#{id}> rdfs:subClassOf* ?a .
    }
  SPARQL
  JSON.parse(sparql(q, format: 'application/sparql-results+json'))
    .dig('results', 'bindings')
    .each {|b| ancestors << b['a']['value'] }
end
warn "collected #{ancestors.size} taxa (seeds + ancestors)"

# 全タクソン分の triple を一括で取得
ancestors.to_a.each_slice(500).with_index do |slice, i|
  warn "  dumping triples for batch #{i + 1} (#{slice.size} taxa) ..."
  values = slice.map {|u| "<#{u}>" }.join(' ')
  q = <<~SPARQL
    CONSTRUCT { ?t ?p ?o }
    WHERE {
      VALUES ?t { #{values} }
      ?t ?p ?o .
    }
  SPARQL
  puts
  puts sparql(q)
end
