#!/usr/bin/env ruby -w

require 'csv'
require 'json'
#require 'pp'

# https://github.com/dbcls/rdfsummit/blob/master/insdc2ttl/insdc2ttl.rb#L237-L243
#def new_feature_uri(feature, from, to, strand, count = false)
#    if count
#      "<#{@sequence_id}#feature:#{from}-#{to}:#{strand}:#{feature}.#{count}>"
#    else
#      "<#{@sequence_id}#feature:#{from}-#{to}:#{strand}:#{feature}>"
#    end
#end

filename = ARGV.shift
i = 0
cache ={}
hash = Hash.new { |h,k| h[k] = Hash.new { |hh,kk| hh[kk] = {'location' => '', 'qualifiers' => []} } }
CSV.foreach(filename, :col_sep => "\t") do |row|
    entry,feature,location,qualifier, qualifier_value =  row
    if i == 0
        cache = { entry: entry, feature: feature, location: location }
        feature_id = "#{entry}#feature:#{location}:#{feature}"
        hash[entry][feature_id]['location'] = location
        hash[entry][feature_id]['feature'] = feature
        hash[entry][feature_id]['entry']  = entry
    else
        #idx = (cache[:entry] == entry and cache[:feature] == feature and cache[:location] == location)?  '.2' : ''
        idx = ''
        cache[:entry] = entry unless entry.nil?
        cache[:feature] = feature unless feature.nil?
        cache[:location] = location unless location.nil?
        feature_id = "#{cache[:entry]}#feature:#{cache[:location]}:#{cache[:feature]}#{idx}"
        hash[cache[:entry]][feature_id]['location'] = cache[:location]
        hash[cache[:entry]][feature_id]['feature'] = cache[:feature]
        hash[cache[:entry]][feature_id]['entry']  = cache[:entry]
    end
    hash[cache[:entry]][feature_id]['qualifiers'] << { key:qualifier, value: qualifier_value}
    i +=1 
end

puts JSON.pretty_generate(hash)

#puts JSON.generate(hash)
