#!/bin/bash -l
#set -e

if [ -z "$BASE_DIR" ] || [ -z "$VIRTUOSO_CONTAINER_NAME" ] || [ -z "$VIRT_PORT" ]; then
  echo "require environment variable BASE_DIR, VIRTUOSO_CONTAINER_NAME, VIRT_PORT"
  exit 1;
fi

LOG()
{
 echo `date +'%Y/%m/%d %H:%M:%S'` $1
}

LOG "start update"
LOG "copy dbfile"
cp /data1/ddbj/DDBJValidator/data_updater/dbfile/virtuoso.db $VIRT_HOME/virtuoso.db.new

cd $BASE_DIR
active_container="$(docker-compose ps | grep virtuoso | grep Up |  wc -l)"
if [[ $active_container -gt 0 ]]; then
  LOG "shutdown virtuoso"
  docker-compose exec -T virtuoso /opt/virtuoso-opensource/bin/isql 1111 dba dba exec="shutdown();"
fi


LOG "switch virtuoso.db"
cd $VIRT_HOME
if [ -e $VIRT_HOME/virtuoso.db ]; then
  mv $VIRT_HOME/virtuoso.db $VIRT_HOME/virtuoso.db.old
fi
dbfiles=($VIRT_HOME/virtuoso.pxa $VIRT_HOME/virtuoso-temp.db $VIRT_HOME/virtuoso.trx)
for dbfile in ${dbfiles[@]}
do
  if [ -e ${dbfile} ]; then
    rm ${dbfile}
  fi
done
mv $VIRT_HOME/virtuoso.db.new $VIRT_HOME/virtuoso.db


LOG "restart virtuoso"
cd $BASE_DIR
docker-compose up -d virtuoso

while :
do
  length="$(curl -fsSL http://localhost:${VIRT_PORT} | wc -l)"
  if [[ $length -ne 0 ]]; then
    break
  fi
  sleep 1
done
LOG "end"

rm $VIRT_HOME/virtuoso.db.old
