# frozen_string_literal: true
source "https://rubygems.org"

group :development do
  gem 'sinatra-reloader'
end

gem "rack"
gem "sinatra"
gem "sinatra-contrib"
gem "haml"
gem "geocoder"
gem "pg"
gem "minitest"
gem "erubis"
gem "nokogiri"
gem "unicorn", "~> 5.5.0.1.g6836"
gem "mail"
gem 'unicorn-worker-killer'
